name: client_data
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: ">=3.8.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.6.8
  equatable: ^2.0.7
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  http: ^1.2.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  matcher: ^0.12.17
  meta: ^1.16.0
  platform: ^3.1.6
  shared_data:
    path: ../shared_data

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  hive_ce_generator: ^1.9.2
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.1
  very_good_analysis: ^9.0.0
