name: auth_server
description: Starting point for a Serverpod module.

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  dart_jsonwebtoken: 3.2.0
  google_secret_manager: ^1.1.0
  pointycastle: ^4.0.0
  serverpod: 2.9.1
  serverpod_serialization: 2.9.1
  serverpod_shared: 2.9.1
  shared_data:
    path: ../../../packages/shared_data
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  serverpod_test: 2.9.1
  test: ^1.24.0

dependency_overrides:
  pointycastle: 4.0.0
