-- DDL generated by Postico 2.0.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE auth_users (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uid uuid DEFAULT gen_random_uuid(),
    "apiKey" character varying(32),
    email character varying(255),
    "isActive" boolean,
    password text,
    "lastLogin" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT now(),
    "updatedAt" timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX auth_users_pkey ON auth_users(id int4_ops);
CREATE INDEX auth_user_uid ON auth_users(uid uuid_ops);
CREATE INDEX "auth_user_apiKey" ON auth_users("apiKey" text_ops);
CREATE INDEX email ON auth_users(email text_ops);
CREATE INDEX "createdAt" ON auth_users("createdAt" timestamptz_ops);
