// ignore_for_file: always_put_required_named_parameters_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:logging/logging.dart';
import 'package:shared_data/shared_data.dart';

part 'user.freezed.dart';
part 'user.g.dart';

// ignore: unused_element
final _log = Logger('shared_data.models.User');

/// {@template BaseUser}
/// User varients emitted by various layers of the authentication system.
/// {@endtemplate}
@Freezed()
sealed class BaseUser with _$BaseUser {
  /// Container for the active user's information. Only used for the active user
  /// after their account is fully created.
  ///
  /// All users start out as [SocialUser] instances when they are first returned
  /// from the social auth provider but are eventually promoted to a full
  /// [AuthUser] after being saved to the database.
  ///
  /// See also:
  ///   [SocialUser] - Partially saved users.
  const factory BaseUser.auth({
    /// Unique identifier. Generated by Firestore as the primary Uid and used
    /// for any relations.
    required String id,

    /// Special information set by the server and used to verify this session
    /// between multiple backends.
    String? jwt,

    /// Unique identifier prepended to all logging statements for this user.
    /// Not sensitive.
    required String loggingId,

    /// User's email address. Null for anonymous users and possibly some social
    /// auth situations.
    String? email,

    /// Origin timestamp of the user.
    required DateTime createdAt,

    /// Last verifying auth provider for this user.
    required AuthProvider lastAuthProvider,

    /// All providers ever activated for this user.
    required Set<AuthProvider> allProviders,
  }) = AuthUser;

  /// A raw user returned by the social auth provider. Instances of [SocialUser]
  /// exist to be promoted to fully-saved [AuthUser] objects.
  const factory BaseUser.socialUser({
    /// Unique identifier. Generated by the social auth provider..
    required String id,

    /// User's email address. Null for anonymous users and possibly some social
    /// auth situations.
    String? email,

    /// Auth method used to create this new account. This value is known when
    /// the user is created, but not necessarily known when the user is later
    /// emitted from the stream.
    AuthProvider? provider,

    /// Origin timestamp of this user.
    required DateTime createdAt,
  }) = SocialUser;

  const BaseUser._();

  /// Deserializes a raw data into an [BaseUser] instance.
  factory BaseUser.fromJson(Json json) => _$BaseUserFromJson(json);

  /// True if the original source of this user's session was
  /// [AuthProvider.anonymous]. This means a user's session cannot be recovered
  /// if they lose access to their device.
  bool get isAnonymous => switch (this) {
        AuthUser(:final lastAuthProvider) =>
          lastAuthProvider == AuthProvider.anonymous,
        SocialUser(:final provider) => provider == AuthProvider.anonymous,
      };

  /// True if the original source of this user's session was something other
  /// than [AuthProvider.anonymous]. This means a user's session CAN be
  /// recovered if they lose access to their device.
  bool get isNotAnonymous => !isAnonymous;

  /// True if the user's email value is non-null and not-empty.
  bool get hasEmail => email != null && email!.isNotEmpty;

  /// Meta information to make [AuthUser] objects pluggable with the
  /// rest of the data layer.
  static Bindings<AuthUser> get authUserBindings => Bindings<AuthUser>(
        fromJson: AuthUser.fromJson,
        getDetailUrl: (id) => ApiUrl(path: 'authUsers/$id'),
        getListUrl: () => const ApiUrl(path: 'authUsers'),
        toJson: (AuthUser obj) => obj.toJson(),
        getId: (AuthUser obj) => obj.id,
      );
}

/// Sources of user authentication.
enum AuthProvider {
  /// Indicates a user's account was not verified by any third party service
  /// or even an email and password combination. The app knows close to nothing
  /// about these users.
  @JsonValue('anonymous')
  anonymous,

  /// Auth provided by Google SSO.
  @JsonValue('google')
  google,

  /// Auth provided by Apple SSO.
  @JsonValue('apple')
  apple,

  /// Auth provided by an email and password.
  @JsonValue('email')
  email;

  /// Serializer for AuthProvider.
  String toJson() => name;

  /// Deserializer for AuthProvider.
  static AuthProvider fromJson(Object serialized) {
    if (serialized is! String) {
      throw Exception(
        'Unexpected type for serialized AuthProvider ${serialized.runtimeType}',
      );
    }
    return AuthProvider.values.byName(serialized);
  }
}

/// {@template Profile}
/// Container for all users of the app in relation to activities like posts,
/// likes, or similar.
///
/// Apps should extend this class with their own `User` model and supply that
/// as the generic type whenever they see `Class<T extends Profile>`.
/// {@endtemplate}
// abstract class Profile {
//   /// {@macro Profile}
//   const Profile({this.id, this.username, this.photo});

//   /// Primary key of this record. Non-null after the objecth as been saved to
//   /// the database.
//   final String? id;

//   /// Social handle of this [Profile] in the app.
//   final String? username;

//   /// Cloud location of this user's profile photo.
//   final String? photo;
// }

/// Sealed union class for credentials from all supported social platforms.
@Freezed()
sealed class SocialCredential with _$SocialCredential {
  /// Mock social credential information representing an email login.
  /// The password is not stored here, as Firebase Auth's backend handles that.
  const factory SocialCredential.email({
    /// Email used to sign in.
    required String email,

    /// Password used to sign in. Required to propagate email sign-ins between
    /// auth services. Should never be stored on the client or in plain text on
    /// the server.
    required String password,
  }) = EmailCredential;

  /// Social credential information supplied by Apple.
  const factory SocialCredential.apple({
    /// An identifier associated with the authenticated user.
    ///
    /// This will always be provided on iOS and macOS systems. On Android,
    /// however, this will not be present.
    /// This will stay the same between sign ins, until the user deauthorizes
    /// your App.
    ///
    /// Not-null in our implementation because Apple Sign-In is not offered on
    /// Android.
    required String? userIdentifier,

    /// The users given name, in case it was requested.
    /// You will need to provide the [AppleIDAuthorizationScopes.fullName] scope
    /// to the [AppleIDAuthorizationRequest] for requesting this information.
    ///
    /// This information will only be provided on the first authorizations.
    /// Upon further authorizations, you will only get the [userIdentifier],
    /// meaning you will need to store this data securely on your servers.
    /// For more information see:
    /// https://forums.developer.apple.com/thread/121496
    required String? givenName,

    /// The users family name, in case it was requested.
    /// You will need to provide the [AppleIDAuthorizationScopes.fullName] scope
    /// to the [AppleIDAuthorizationRequest] for requesting this information.
    ///
    /// This information will only be provided on the first authorizations.
    /// Upon further authorizations, you will only get the [userIdentifier],
    /// meaning you will need to store this data securely on your servers.
    /// For more information see:
    /// https://forums.developer.apple.com/thread/121496
    required String? familyName,

    /// The users email in case it was requested.
    /// You will need to provide the [AppleIDAuthorizationScopes.email] scope to
    /// the [AppleIDAuthorizationRequest] for requesting this information.
    ///
    /// This information will only be provided on the first authorizations.
    /// Upon further authorizations, you will only get the [userIdentifier],
    /// meaning you will need to store this data securely on your servers.
    /// For more information see:
    /// https://forums.developer.apple.com/thread/121496
    required String? email,

    /// The verification code for the current authorization.
    ///
    /// This code should be used by your server component to validate the
    /// authorization with Apple within 5 minutes upon receiving it.
    required String authorizationCode,

    /// A JSON Web Token (JWT) that securely communicates information about the
    /// user to your app.
    required String? identityToken,

    /// The `state` parameter that was passed to the request.
    ///
    /// This data is not modified by Apple.
    required String? state,
  }) = AppleCredential;

  /// Social credential information supplied by Apple.
  const factory SocialCredential.google({
    /// The display name of the signed in user.
    ///
    /// Not guaranteed to be present for all users, even when configured.
    required String? displayName,

    /// The email address of the signed in user.
    ///
    /// Applications should not key users by email address since a Google
    /// account's email address can change. Use [id] as a key instead.
    ///
    /// _Important_: Do not use this returned email address to communicate the
    /// currently signed in user to your backend server. Instead, send an ID
    /// token which can be securely validated on the server. See [idToken].
    required String email,

    /// The unique ID for the Google account. Called [id] in the package.
    ///
    /// This is the preferred unique key to use for a user record.
    ///
    /// _Important_: Do not use this returned Google ID to communicate the
    /// currently signed in user to your backend server. Instead, send an ID
    /// token which can be securely validated on the server. See [idToken].
    required String uniqueId,

    /// The photo url of the signed in user if the user has a profile picture.
    ///
    /// Not guaranteed to be present for all users, even when configured.
    required String? photoUrl,

    /// A token that can be sent to your own server to verify the authentication
    /// data.
    required String? idToken,

    /// Server auth code used to access Google Login
    required String? serverAuthCode,
  }) = GoogleCredential;

  const SocialCredential._();

  /// Deserializes a raw data into an [AuthUser] instance.
  factory SocialCredential.fromJson(Json json) =>
      _$SocialCredentialFromJson(json);

  /// Meta information to make [SocialCredential] objects pluggable with the
  /// rest of the data layer.
  static Bindings<SocialCredential> get bindings => Bindings<SocialCredential>(
        fromJson: SocialCredential.fromJson,
        toJson: (SocialCredential obj) => obj.toJson(),
        getId: (SocialCredential obj) => throw UnimplementedError(
          'Should not need to get SocialCredential Id',
        ),
        getDetailUrl: (String id) => throw UnimplementedError(
          'Should not need to get detail Url for SocialCredential',
        ),
        getListUrl: () => const ApiUrl(path: 'credentials'),
      );

  /// Pulls the email out of the credential. Required only because some types
  /// are nullable and some are not.
  String? getEmail() => switch (this) {
        EmailCredential() => email,
        AppleCredential() => email,
        GoogleCredential() => email,
      };
}

/// {@template AuthUserConverter}
/// {@endtemplate}
class AuthUserConverter extends JsonConverter<AuthUser, Json> {
  /// {@macro AuthUserConverter}
  const AuthUserConverter();
  @override
  AuthUser fromJson(Json json) => AuthUser.fromJson(json);

  @override
  Json toJson(AuthUser object) => object.toJson();
}
