name: shared_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.0-213.0.dev

# Add regular dependencies here.
dependencies:
  crypt: ^4.3.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  matcher: ^0.12.16
  meta: ^1.16.0
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^8.0.0-rc.1
