name: client_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-213.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.2
  client_auth:
    path: ../../packages/client_auth
  common:
    path: ../common
  dartz: ^0.10.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.24.5
  firebase_ui_auth: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^7.6.4
  go_router: ^13.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_data:
    path: ../../packages/shared_data

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
