name: auth_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.8.1

dependencies:
  serverpod_client: 2.9.1
  serverpod_serialization: 2.9.1
  shared_data:
    path: ../../../packages/shared_data

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
