include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    omit_local_variable_types: false

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**.g.dart"

formatter:
  trailing_commas: preserve
