name: client_auth
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.2.0-220.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  client_data_firebase:
    path: ../client_data_firebase
  cloud_firestore: ^5.6.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.5.4
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  matcher: ^0.12.16
  platform: ^3.1.3
  shared_data:
    path: ../shared_data
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^8.0.0-rc.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
