name: auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.0-213.0.dev

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  db:
    path: ../db
  shared_data:
    path: ../../../shared_data

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
