name: auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.0-213.0.dev

# Add regular dependencies here.
dependencies:
  common:
    path: ../../../common
  dartz: ^0.10.1
  db:
    path: ../db
  drift: ^2.14.1
  drift_postgres:
    path: ../../../../../../simolus3/drift/extras/drift_postgres
  postgres: ^3.0.4
  shared_data:
    path: ../../../../packages/shared_data

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  test: ^1.24.0
  very_good_analysis: ^5.1.0
