name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0-213.0.dev

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_data:
    path: ../../packages/shared_data

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.0
  very_good_analysis: ^5.1.0
