include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  rules:
    file_names: false
    flutter_style_todos: false
    public_member_api_docs: true

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "build/**"
