include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  rules:
    public_member_api_docs: true
    flutter_style_todos: false

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
